### ISSUE TITLE
crear un docker compose

### ISSUE THREAD

**Issue by mauroalderete** [AldereteSergio/p2p-tracker#8]
crear un docker compose que permita usar telegraf + fluxdb + grafana y el servicio p2p-tracker para ingestar la salida stdout del servicio y almacenar los registros de tiempo en fluxdb

se podria usar algo asi:

``` yaml
version: '3'

services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  telegraf:
    image: telegraf:latest
    depends_on:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    config:
      - telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  p2p-tracker:
    image: p2p-tracker:latest

volumes:
  influxdb-data:
  grafana-data:

networks:
  default:
    external:
      name: my-network

```
